# Generated by Django 4.2.6 on 2024-04-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
