# Generated by Django 4.2.6 on 2024-04-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
