# Generated by Django 4.2.6 on 2024-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
