# Generated by Django 4.2.6 on 2024-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_order_product_id_alter_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
